In [1]:
import pandas as pd

df = pd.read_csv("data/appl.csv")  # or whichever stock you choose
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/appl.csv'

In [2]:
import os
print(os.listdir("data"))

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data'

In [3]:
import os
print("CURRENT:", os.getcwd())

CURRENT: c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 1\Nova_Financial_Solution_Assignment\nova-financial-analysis-week1\notebooks

In [4]:
import os

base_path = os.path.abspath("..")
print(base_path)

c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 1\Nova_Financial_Solution_Assignment\nova-financial-analysis-week1

In [5]:
df = pd.read_csv(os.path.join(base_path, "data", "appl.csv"))
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\gebre\\OneDrive\\Documents\\Programming\\KIAM 10 academy\\Week 1\\Nova_Financial_Solution_Assignment\\nova-financial-analysis-week1\\data\\appl.csv'

In [6]:
import pandas as pd

df = pd.read_csv("data/aapl.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/aapl.csv'

In [7]:
import pandas as pd

df = pd.read_csv("data/AAPL.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/AAPL.csv'

In [8]:
import os

print("CURRENT DIR:", os.getcwd())
print("DATA EXISTS:", os.path.exists("data"))

if os.path.exists("data"):
    print("DATA FILES:", os.listdir("data"))

CURRENT DIR: c:\Users\gebre\OneDrive\Documents\Programming\KIAM 10 academy\Week 1\Nova_Financial_Solution_Assignment\nova-financial-analysis-week1\notebooks
DATA EXISTS: False

In [9]:
import pandas as pd
import os

base_path = os.path.dirname(os.getcwd())  # goes from notebooks → project root

file_path = os.path.join(base_path, "data", "AAPL.csv")

df = pd.read_csv(file_path)
df.head()

         Date     Close      High       Low      Open      Volume
0  2009-01-02  2.721686  2.730385  2.554037  2.575630   746015200
1  2009-01-05  2.836553  2.884539  2.780469  2.794266  1181608400
2  2009-01-06  2.789767  2.914229  2.770872  2.877641  1289310400
3  2009-01-07  2.729484  2.774170  2.706990  2.753477   753048800
4  2009-01-08  2.780169  2.793666  2.700393  2.712090   673500800

In [10]:
print(os.listdir(os.path.join(os.path.dirname(os.getcwd()), "data")))

['.DS_Store', '._.DS_Store', '._AAPL.csv', '._AMZN.csv', '._GOOG.csv', '._META.csv', '._NVDA.csv', 'AAPL.csv', 'AMZN.csv', 'GOOG.csv', 'META.csv', 'NVDA.csv']

In [11]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')

df[['Open','High','Low','Close','Volume']] = df[['Open','High','Low','Close','Volume']].astype(float)

df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [12]:
df.describe()

,Date,Close,High,Low,Open,Volume
count,3774,3774.000000,3774.000000,3774.000000,3774.000000,3.774000e+03
mean,2016-07-01 03:40:32.432432,53.841169,54.383801,53.247465,53.801628,2.640640e+08
min,2009-01-02 00:00:00,2.345299,2.459265,2.345299,2.380989,2.404830e+07
25%,2012-09-28 18:00:00,15.050355,15.183043,14.901886,15.007580,9.581845e+07
50%,2016-06-30 12:00:00,26.975808,27.168844,26.836844,27.010205,1.667348e+08
75%,2020-03-31 18:00:00,74.664204,75.252383,73.553555,74.127927,3.777410e+08
max,2023-12-29 00:00:00,196.256592,197.752460,195.156944,196.167437,1.880998e+09
std,NaN,55.064042,55.627235,54.440128,55.009182,2.345629e+08

In [13]:
df.shape

(3774, 6)

In [15]:
df['SMA_20'] = df['Close'].rolling(window=20).mean()
df['SMA_50'] = df['Close'].rolling(window=50).mean()

df['EMA_20'] = df['Close'].ewm(span=20, adjust=False).mean()
df['EMA_50'] = df['Close'].ewm(span=50, adjust=False).mean()

In [16]:
df[['Close','SMA_20','SMA_50','EMA_20','EMA_50']].head(30)

       Close    SMA_20  SMA_50    EMA_20    EMA_50
0   2.721686       NaN     NaN  2.721686  2.721686
1   2.836553       NaN     NaN  2.732626  2.726191
2   2.789767       NaN     NaN  2.738068  2.728684
3   2.729484       NaN     NaN  2.737250  2.728715
4   2.780169       NaN     NaN  2.741338  2.730733
5   2.716589       NaN     NaN  2.738981  2.730179
6   2.659007       NaN     NaN  2.731364  2.727388
7   2.630514       NaN     NaN  2.721760  2.723589
8   2.559135       NaN     NaN  2.706271  2.717139
9   2.500652       NaN     NaN  2.686689  2.708650
10  2.469163       NaN     NaN  2.665972  2.699258
11  2.345299       NaN     NaN  2.635432  2.685377
12  2.484158       NaN     NaN  2.621025  2.677486
13  2.650008       NaN     NaN  2.623785  2.676409
14  2.650008       NaN     NaN  2.626282  2.675373
15  2.688398       NaN     NaN  2.632198  2.675884
16  2.721087       NaN     NaN  2.640664  2.677657
17  2.825157       NaN     NaN  2.658235  2.683441
18  2.789167       NaN     NaN  2.670704  2.687587
19  2.703094  2.662455     NaN  2.673789  2.688195
20  2.744479  2.663594     NaN  2.680521  2.690403
21  2.788567  2.661195     NaN  2.690812  2.694252
22  2.805662  2.661990     NaN  2.701750  2.698621
23  2.892936  2.670162     NaN  2.719958  2.706241
24  2.990708  2.680689     NaN  2.745744  2.717397
25  3.074382  2.698579     NaN  2.777042  2.731396
26  2.934024  2.712330     NaN  2.791993  2.739343
27  2.903732  2.725991     NaN  2.802635  2.745789
28  2.977211  2.746895     NaN  2.819261  2.754865
29  2.973911  2.770558     NaN  2.833990  2.763455